name: CI/CD Pipeline for MySQL DB

on:
  push:
    branches:
      - main

jobs:
  deploy-mysql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: Root@1234
          MYSQL_DATABASE: project_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: List project structure (for debugging)
      run: ls -R

    - name: Install Python and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install mysql-connector-python

    - name: Wait for MySQL to be ready
      run: sleep 30

    - name: Run SQL Scripts (Create Table, Add Column, Seed Data)
      run: |
        mysql -h 127.0.0.1 -u root -pRoot@1234 -D project_db -e "SOURCE sql/create_table.sql;"
        mysql -h 127.0.0.1 -u root -pRoot@1234 -D project_db -e "SOURCE sql/add_column.sql;"
        mysql -h 127.0.0.1 -u root -pRoot@1234 -D project_db -e "SOURCE sql/insert_data.sql;"

    - name: Run Python Script for Concurrent Queries
      run: python3 scripts/multi_thread_queries.py

    - name: Validate Table and Data
      run: |
        echo "✅ ClimateData Table Structure:"
        mysql -h 127.0.0.1 -u root -pRoot@1234 -D project_db -e "DESCRIBE ClimateData;"

        echo "✅ Total Records Inserted:"
        mysql -h 127.0.0.1 -u root -pRoot@1234 -D project_db -e "SELECT COUNT(*) FROM ClimateData;"

        echo "✅ Sample Data:"
        mysql -h 127.0.0.1 -u root -pRoot@1234 -D project_db -e "SELECT * FROM ClimateData LIMIT 5;"
